language: java
jdk:
- oraclejdk8
services:
  - mysql
before_install:
- pip install codecov
- mysql -e "create database IF NOT EXISTS test;" -uroot

notifications:
  slack: veigadevteam:2ZWGQ2aH21BZOdjj9dNm2nlX
after_success:
  - codecov
